version: '3'

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag-api-service
    ports:
      - "8080:8080"
    environment:
      - VECTOR_STORE=faiss
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chromadb
    volumes:
      - ./documents:/app/documents
      - ./vector_store:/app/vector_store
    depends_on:
      - chromadb
      - ollama

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_DEBUG=true
    volumes:
      - ./chroma_data:/chroma/db

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_models:/root/.ollama
    command: serve