# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\x08\x64ocument\"2\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"6\n\x0eUploadResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x0f\x44ocumentRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"5\n\x10\x44ocumentResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"&\n\x0f\x44ownloadRequest\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\"\"\n\rDocumentChunk\x12\x11\n\tfile_data\x18\x01 \x01(\x0c\x32\xe6\x01\n\x0f\x44ocumentService\x12\x43\n\x0eUploadDocument\x12\x17.document.UploadRequest\x1a\x18.document.UploadResponse\x12\x44\n\x0bGetDocument\x12\x19.document.DocumentRequest\x1a\x1a.document.DocumentResponse\x12H\n\x10\x44ownloadDocument\x12\x19.document.DownloadRequest\x1a\x17.document.DocumentChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=28
  _globals['_UPLOADREQUEST']._serialized_end=78
  _globals['_UPLOADRESPONSE']._serialized_start=80
  _globals['_UPLOADRESPONSE']._serialized_end=134
  _globals['_DOCUMENTREQUEST']._serialized_start=136
  _globals['_DOCUMENTREQUEST']._serialized_end=174
  _globals['_DOCUMENTRESPONSE']._serialized_start=176
  _globals['_DOCUMENTRESPONSE']._serialized_end=229
  _globals['_DOWNLOADREQUEST']._serialized_start=231
  _globals['_DOWNLOADREQUEST']._serialized_end=269
  _globals['_DOCUMENTCHUNK']._serialized_start=271
  _globals['_DOCUMENTCHUNK']._serialized_end=305
  _globals['_DOCUMENTSERVICE']._serialized_start=308
  _globals['_DOCUMENTSERVICE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
